### ISSUE TITLE
Add nav menu and finalize header

### ISSUE THREAD

**Issue by skanderm** [orcasound/orcasite#191]

**Comment by paulcretu** [comment]
Some ideas from the figma (needs updating with latest logo):

#### Desktop
![image](https://github.com/orcasound/orcasite/assets/1069628/aeeb3988-3a0c-4561-a21f-533ec17f7308)

#### Mobile
![image](https://github.com/orcasound/orcasite/assets/1069628/bef7abc8-089e-44b7-a4de-3699d2296923)
![image](https://github.com/orcasound/orcasite/assets/1069628/f74640ab-d11a-4808-8ad9-bc98d4459a01)


### Unresolved

#### Nav items

The nav items probably need to be changed. Some [ideas here](https://docs.google.com/drawings/d/13ZJOLbxa7bawib3xVQCdNwTP_0P-Xa5BequhSIbDwRg/edit):

![image](https://github.com/orcasound/orcasite/assets/1069628/f1b0ada8-b6ae-4346-8538-3d312b4fbc53)

#### Footer

![image](https://github.com/orcasound/orcasite/assets/1069628/eff5e601-f905-4380-8040-e77c8a1f2d92)

What do we do with the footer? It'll look funny with the player being at the bottom now. Probably move into the top nav menu (expandable "more"?)
