### ISSUE TITLE
Detection dialog closes on stream stop

### ISSUE THREAD

**Issue by paulcretu** [orcasound/orcasite#198]
#### Expected
When submitting a detection, the detection dialog/modal should stay open until user submits the detection or closes the dialog/modal

#### Actual
The detection dialog closes if the stream stops or errors, because the `DetectionDialog` component gets unmounted when the stream URL is `undefined`

**Comment by skanderm** [comment]
This is due to the conditional:

```
(playerStatus === "playing" || playerStatus === "loading") &&
        currentFeed &&
        timestamp &&
```

We should just pass a controlled `open` status to the dialog.
