### ISSUE TITLE
Add listener count to feed list

### ISSUE THREAD

**Issue by paulcretu** [orcasound/orcasite#223]
It would be nice if we could show the number of listeners next to each feed in the feed list:

<img width="583" alt="image" src="https://github.com/orcasound/orcasite/assets/1069628/4e992051-ce79-4e54-b675-f19d2625ec2b">

This is harder than it looks because of how [Presence](https://hexdocs.pm/phoenix/Phoenix.Presence.html) works—we'll probably need a new websocket channel for getting listener counts without actually joining each feed's channel.

**Comment by skanderm** [comment]
Added in #245

**Comment by skanderm** [comment]
<img width="493" alt="image" src="https://github.com/orcasound/orcasite/assets/997770/41c694d6-10f8-451a-9ddb-b5f0f07e2ac4">
