### ISSUE TITLE
Link to Reports within "thank you for submitting" modal

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcasite#240]
**Problem (minor)**
The modal message that pops up to say "Thank you for submitting." after annotating the livestream could be more meaningful.

<img width="845" alt="Screenshot 2023-10-21 at 7 58 30 PM" src="https://github.com/orcasound/orcasite/assets/14044595/69c95e34-0d1a-43ee-b8f6-92851b29ccb1">

**Describe the solution you'd like**
1) The modal could be improved slightly by saying "Thank you for reporting" (because the v3 button says "Report Sound," so "Submitting" isn't quite as accurate any more).
2) A second line could read "View reports here" and be hypertext linked (in a new tab, so live-listening can continue) to [https://beta.orcasound.net/reports](https://beta.orcasound.net/reports) or a similar listing of recent human (and machine?) detections.

**Describe alternatives you've considered**
A different second line could just offer an explanation for why we are thankful, e.g. "Thank you! Your report helps train people and AI to listen for whales."

**Additional context**
Current view of report page:
<img width="1225" alt="Screenshot 2023-10-21 at 7 57 13 PM" src="https://github.com/orcasound/orcasite/assets/14044595/03749fef-6b85-4d56-8507-fd787395347b">

**Comment by skanderm** [comment]
If we'll be linking listeners to the reports page, we may want to think a bit more (and research) about the design for the report page. Perhaps some education about how that data is used, among other things.

**Comment by paulcretu** [comment]
I don't see any reason not to just go ahead and make the quick tweaks to the modal right away—we can always update it once we have a better design.

@skanderm @Filadora @scottveirs Do you think the reports page is in a good enough state to "launch" and make it official? There are tons of things to improve but I think it's usable enough…

**Comment by Filadora** [comment]
@paulcretu I agree about starting with small improvements and keep working on that. The reports page looks usable and it would be great to hear any feedback from the users to see whether we are moving in the right direction with further improvements.

**Comment by Filadora** [comment]
I've added a Figma page for this: https://www.figma.com/file/41JuvNkXJhTUob8HMsJiNC/Orcasite%3A-design-updates?type=design&node-id=1228%3A8643&mode=design&t=OJDAMZwWXGpsHsFZ-1

As a first step improvement, we could add a button that would take users to the reports: 

<img width="594" alt="Screenshot 2024-03-01 at 12 06 35 PM" src="https://github.com/orcasound/orcasite/assets/116315084/a67caa34-669c-4862-9946-6f3b72a12788">

Cattleya was working on these drafts, originally we were thinking about suggesting the "community feed" page:

<img width="242" alt="Screenshot 2024-03-01 at 12 06 42 PM" src="https://github.com/orcasound/orcasite/assets/116315084/20c500f9-3079-4ef1-9286-d78fb6d8831e">

<img width="241" alt="Screenshot 2024-03-01 at 12 06 49 PM" src="https://github.com/orcasound/orcasite/assets/116315084/ad80c587-99cf-44d7-8e38-07939a42e814">
