### ISSUE TITLE
Add GA event tracking to new Learn button on landing page

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcasite#247]
Before the public launch of v3, it would be ideal to be able to track how often users elect to use the new `Learn the Sounds` button. Other similar events are tracked with Google Analytics.

**Describe the solution you'd like**
Add GA4 event tracking to the new `Learn the Sounds` button

**Additional context**
It's probably worth implementing a solution to this issue in the beta testing site, but double checking the connection with Google Analytics keeps working after the transition to production.

**Comment by skanderm** [comment]
Added in #249
