### ISSUE TITLE
Selecting new node for listening does not change feed

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcasite#3]
On live.orcasound.net you can currently click on a hydrophone node and listen to it's live feed (e.g. Bush Point). But if you then select a new node (e.g. Orcasound Lab), the old feed continues to play, even upon subsequent clicks of the "Listen to" button or the play/pause button.

If you reload live.orcasound.net however, and then first select Orcasound Lab for listening, it's feed plays successfully. So, it seems the inter-linking is broken, rather than one of the feeds being down...

**Comment by skanderm** [comment]
Fixed earlier!
