### ISSUE TITLE
Making the Orcasound logo a button that takes to the Home Screen

### ISSUE THREAD

**Issue by Filadora** [orcasound/orcasite#326]
**Issue**

Users were lost trying to get back to the home screen from the map view when accessing from the mobile device.

![IMG_6628](https://github.com/orcasound/orcasite/assets/116315084/2bced540-b8d7-4254-8dbe-1bc8aa27bac0)

**Solution**

Making the Orcasound logo a button that takes to the Home Screen.

**Comment by scottveirs** [comment]
Noting/clarifying that this is only an issue on mobile, @paulcretu  et al. On desktop (see screenshots taken today, below), the Orcasound logo allows one way to get back to the landing page from a feed page. The `Home` part of the breadcrumb UI provides another...

![Image](https://github.com/orcasound/orcasite/assets/14044595/0e7d228d-8a9f-4275-a058-a66ffe773b3c)

...but interestingly the breadcrumb UI disappears if one follows the `Listen` part of the feed page breadcrumb UI:

![Image](https://github.com/orcasound/orcasite/assets/14044595/eb595503-f9a1-455c-b950-b2c3f07ec934)
