### ISSUE TITLE
To rename "Start Listening" button to "Select hydrophone location"

### ISSUE THREAD

**Issue by Filadora** [orcasound/orcasite#327]
**Issue**

Users were confused about the Start Listening button. Users assumed that it would take them to a random location and that they would start listening right away.

<img width="493" alt="Screenshot 2024-01-30 at 4 32 10 PM" src="https://github.com/orcasound/orcasite/assets/116315084/30eeaeb8-c926-4854-ac94-ed27ae930bb1">

**Solution**

To rename the "Start Listening" button to "Select hydrophone location"

<img width="381" alt="Screenshot 2024-01-25 at 3 31 25 PM" src="https://github.com/orcasound/orcasite/assets/116315084/f9ebb88c-2ee4-48a2-ad9d-a0bcb2d5fe36">

**Comment by skanderm** [comment]
How do you feel about making it "select listening location"? Hydrophone might be a bit too specific. Happy to defer though.

**Comment by mrose15** [comment]
@paulcretu @skanderm @Filadora I wanted to follow up on @skanderm's question regarding the buttons name before I made this change. What do we think? I think Skander might be right on this one. His suggestion adds in the action the user will be taking (ie: 'listening').

**Comment by paulcretu** [comment]
"Select listening location" sounds better to me too, as "hydrophone" is more technical and less familiar. @Filadora if I remember correctly, you had some user research with "Select hydrophone location" instead? Were the users familiar with what a hydrophone is?

**Comment by Filadora** [comment]
@mrose15 I double-checked the previous research data, we can call it "Select listening location", there is no specific need to call it "Select hydrophone location"

**Comment by paulcretu** [comment]
Resolved by #336
