### ISSUE TITLE
Redeploy "Version 2" of Orcasite

### ISSUE THREAD

**Issue by UXBrendan** [orcasound/orcasite#385]
Redeploy previous version of Orcasite in a beta environment, including live streaming of Haro Strait (Orcasound Lab), Port Townsend, and Bush Point. Please include all feature functionality but do not send sound reports to https://live.orcasound.net/reports.

Please reach out to @UXBrendan with any questions.

**Comment by paulcretu** [comment]
A few weeks ago I made a quick attempt to redeploy the [v2-ui tag](https://github.com/orcasound/orcasite/tree/v2-ui) to Heroku as a review app. First I had to make some adjustments to the Heroku app.json config to even get it to start building, but then ran into the following error:

![image](https://github.com/orcasound/orcasite/assets/1069628/a937beb4-5df5-4247-8ce8-f21e308bdb53)

**Comment by mrose15** [comment]
@UXBrendan With @paulcretu's help, I was able to get the v2 version up and running. Please let me know if everything looks correct. https://orcasite-br-v2-redeploy.herokuapp.com/

**Comment by UXBrendan** [comment]
@mrose15 

Thanks! I noticed that there is only "Orcasound Lab" listed in the dropdown. Would it be possible to include the Port Townsend, and Bush Point hydrophone streams?

**Comment by mrose15** [comment]
@UXBrendan Skander pushed the additional streams last week. Let me know if there's any additional issues. If not, I'll close out this ticket. Thanks!

**Comment by UXBrendan** [comment]
Thanks so much for all your help! Support happy and excited about the
redeploy you and Skander did!

**Comment by mrose15** [comment]
@paulcretu @skanderm @UXBrendan Marking closed
