### ISSUE TITLE
Chrome+Safari begins playback at first segment in .m3u8 manifest

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcasite#4]
It would be ideal if player initiated playback closer to real-time...

In the case I examined the down-loaded .m3u8 entry had hundreds of segments listed, but watching in the Javascript Console, playback began at live000.ts -- no matter if the page was reloaded, with or without first clearing the local Safari cache and cookies.

**Comment by paulcretu** [comment]
I don't think this happens any more right @scottveirs? Should we close this issue?
