### ISSUE TITLE
Google Analytics data isn't being collected for the website

### ISSUE THREAD

**Issue by watcher00090** [orcasound/orcasite#43]
Google Analytics data isn't being collected for the website. Brendan got this report:

No Hits
First detected: May 22, 2020 7:57:17 AM
Last detected: Aug 2, 2020 1:07:29 PM
Property Orcasound May 2020 Launch is not receiving hits. Either your site is not receiving any sessions or it is not tagged correctly.
Google Tag Assistant Recordings can help you ensure that your site is tagged correctly.
Learn more: https://support.google.com/analytics/bin/answer.py?answer=1008080&hl=en-US
support.google.comsupport.google.com
Set up the Analytics global site tag - Analytics Help
In this article: Basic instructions Set up data collection based on your type of site

**Comment by saptarsi96** [comment]
Hi, @watcher00090 is the issue still active?

**Comment by watcher00090** [comment]
@saptarsi96 Not really. I recently submitted a pull request which should fix it.

**Comment by paulcretu** [comment]
This is fully resolved now, the "Orcasite live" app is now collecting pageviews and events, and we're no longer using the "Orcasound May 2020 Launch" app
