### ISSUE TITLE
Admin UI fails to play candidate with time close to restart of streaming container

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcasite#66]
**Describe the bug**
This is an edge case (rare) where playback of recorded HLS segments fails within the Orcasound admin UI.

**To Reproduce**
1. Go to live.orcasound.net/admin (logged in as an admin user)
2. View candidate dated 9/1/2021 6:30:09AM
3. Select Play button
4. See spinning progress indicator, but hear no playback

**Expected behavior**
Normally, candidates playback the recorded HLS segments

**Screenshots**
<img width="1745" alt="Screen Shot 2021-09-02 at 9 17 44 AM" src="https://user-images.githubusercontent.com/14044595/131882912-938a79cd-e632-4bcb-a9b0-093df084fba9.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.15.5
 - Browser: Chrome 92.0.4515.159 (Official Build) (x86_64)

**Additional context**
The manifest (.m3u8 file) associated with this bug has 2158 segments (each supposedly 10 seconds long). The Raspberry Pi at this hydrophone location (Orcasound Lab) has a cron job that restarts the streaming container every 6 hours, starting at 00:30 each day. The expected seconds of data in those six hours less the aggregate seconds of data in the relevant S3 bucket (Unix datetime stamp = ) shows the amount of time the restart takes: ~20 seconds [ (3600*6)-(2158*10)=20 ].

The root of this playback failure is probably that the time of the human annotation (06:30:09 in this case) is within a restart period where there was no streaming happening... i.e. within a data gap. Perhaps this happened because the annotator selected the "I hear something interesting" button just after the container had restarted, and as their player reached the final segment available in the latest (then penultimate) S3 folder?

Possible solutions: 

1. Long-term: Shift strategy within `orcanode` repo to avoid any data gaps. For example just stream to a S3 folder continuously without any streaming container restarts.
2. Short-term: Write custom playback code for this edge case
3. Short-term: For each annotation, capture and utilize the time of the button push, not the submit button that is selected after an unknown period during which the user is typing in their annotation text.

**Comment by paulcretu** [comment]
Blocked until candidates/detections view is re-added

**Comment by paulcretu** [comment]
Now that the [/reports](https://live.orcasound.net/reports) view is live, we should investigate if this still happens. Here's a direct link to the candidate in question:

https://live.orcasound.net/reports/cand_02ulWVLEMRhPmVOdxuKCh0

Because of the 15s padding, it starts playing for me but stops halfway through (when the stream ends?)

Solution <span>#</span>3 is already implemented as of https://github.com/orcasound/orcasite/pull/167 so I imagine this should happen very rarely now (a user would have to intentionally make a report during downtime)
