### ISSUE TITLE
Ensure human detection timestamp accurately indicates when the user hears something interesting

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcasite#82]
### The problem

The timestamps of human detections are not always well-aligned with the audio signals that inspired them. This can create confusion when trying to use the labels to find signals of interest, especially short ones like echolocation clicks.

In version 1 the detection timestamp was determined when the user selected the "I hear something interesting" button. This worked well. In version 2, the timestamp was based on when the user completed their free-form text annotation and selected the "SUBMIT" button. Because some users take a while (e.g. minutes) to type in their annotation and hit the SUBMIT button, the annotations were less synchronized with their associated signals, and therefore were less useful.

<img width="1094" alt="Screen Shot 2021-12-15 at 2 35 53 PM" src="https://user-images.githubusercontent.com/14044595/146276118-4ad56c9c-5388-40b6-826b-f925bffeb952.png">

This feature request involves returning to the version 1 method, or something akin to it.

### The proposed solution

In version 3 of the live-listening app and going forward, it would be optimal if human detections were timestamped based on the first indication by the user that they are hearing a signal and want to annotate it. As a community scientist helping label audio data, I want the timestamp for my detection to be established when I first begin the annotation process.

Assuming the v3 annotation UI looks something like what is in the [recent mockups](https://www.figma.com/file/k0lM6w4muG2MMTDdGARSW6/Orcasound-Mobile-%26-Desktop-Listening-App-Redesign?node-id=0%3A1) -- 

<img width="676" alt="Screen Shot 2021-12-15 at 3 00 13 PM" src="https://user-images.githubusercontent.com/14044595/146278286-0bdb56b0-0448-4991-9b53-5d0ee04d24eb.png">

-- then the ideal solution would include generating a timestamp as soon the "I hear something" button is selected. The timestamp should not be affected by how long it takes the user to select default labels (e.g. via the labeling buttons for whale, ship, fish, other), add any comments, and ultimately select the submit button.

<img width="1000" alt="Screen Shot 2021-12-15 at 2 58 15 PM" src="https://user-images.githubusercontent.com/14044595/146277900-623b7ab9-a2bd-4953-bf4c-ba3b39953a64.png">

**Describe alternatives you've considered**
None

### Additional context

Skander and Scott came up with the idea of `detections` vs `candidates`. A detections occur whenever any user annotates the live audio data stream. Candidates are temporal groups of detections. The benefits of this nomenclature are that review of a candidate table is more efficient; instead of listing every record, the algorithm at least begins the process of grouping interesting signals into an acoustic "bout."

Here's an example of the `Candidates` list in the Orcasound admin UI (as of Dec 2021):

<img width="996" alt="Screen Shot 2021-12-15 at 11 59 22 AM" src="https://user-images.githubusercontent.com/14044595/146281310-fa6caaf3-4830-4b80-8396-1560514c1b88.png">

And here's a screenshot of the same data records, but exported from the Heroku Postgres database to provide an [Orcasound data visualization opportunity](https://github.com/orcasound/orcadata/wiki/Data-visualization-opportunities#15-may-2021-data-clip-2000-rows):
 
<img width="1587" alt="Screen Shot 2021-12-15 at 12 27 07 PM" src="https://user-images.githubusercontent.com/14044595/146281317-214024c3-0590-4e83-8a55-f4c4056b61a3.png">

**Notes from an Orcasound Slack thread on 12/15/21 related to this feature request:**

**Paul:**

Just took a look at this too, turns out that yes the timestamp is calculated properly on the backend using the playlist epoch + offset. The problem then is if the offset being sent to the server by the UI is correct. In the [DetectButton component](https://github.com/orcasound/orcasite/blob/master/assets/src/components/DetectButton.js), the offset is indeed calculated right when the button is pressed. Unfortunately we don't use DetectButton anymore, I think that's the button from v1. For v2 it looks like we moved over to DetectionDialog component, which only grabs the offset when the [submit button gets clicked](https://github.com/orcasound/orcasite/blob/master/assets/src/components/DetectionDialog.js#L133-L140) in the dialog/modal.

```
DetectionDialog.js
                   <Button
                    onClick={() => {
                      this.onDetect(submitDetection)
                    }}
                    color="secondary"
                  >
                    SUBMIT
                  </Button>
```

So in short, for v1 detections corresponded to the exact time the button was clicked, and for v2 that's no longer the case and now is dependent on when modal dialog is submitted. 

**Skander:** 

`inserted_at` is when the database entry was made. `playlist_timestamp` is the epoch of the .ts file, and then `player_offset` is actually when the detection happened relative to the .ts file. Like e.g. 5 seconds into a 10-second HLS segment.

**Valentina screenshot**
while reviewing functions within `orcasite` code...

<img width="279" alt="Screen Shot 2021-12-15 at 12 36 28 PM" src="https://user-images.githubusercontent.com/14044595/146280657-df91a38f-54b4-410e-88c2-9d15b9b6254e.png">

**Scott (scientist, not dev!):**

My understanding is that the DateTime is derived from the audio stream by the player knowing two things:

1.  the Unix timestamp (UTC time zone) when the current stream of HLS segments began
2. the offset (in seconds, I think) between that Unix timestamp and the current position of the player in the stream

So, to get the timestamp of the audio data when a user is hearing a signal, you would add 1+2 (and then convert to whatever format and time zone you want)

- Where timestamps get computed (I think) -- https://github.com/orcasound/orcasite/blob/58d0b89e8fc6aca79fd1ff14c8367c50f7e92a92/lib/orcasite/radio/radio.ex
- UTC mentioned here -- https://github.com/orcasound/orcasite/blob/master/assets/src/utils/utils.js

Confirming that offset should have units of seconds, per https://www.unixtimestamp.com/

**Skander:** 

"Lockout stuff is mostly about not getting spammed by bots. The timestamps should be stored as UTC in the db, but it’s possible it’s being displayed in a local timezone in the admin panel

Specifically `field(:timestamp, :utc_datetime)` in 
[https://github.com/orcasound/orcasite/blob/58d0b89e8fc6aca79fd1ff14c8367c50f7e92a92/lib/orcasite/radio/detection.ex
](https://github.com/orcasound/orcasite/blob/58d0b89e8fc6aca79fd1ff14c8367c50f7e92a92/lib/orcasite/radio/detection.ex)

```
detection.ex
defmodule Orcasite.Radio.Detection do
  use Ecto.Schema
  import Ecto.Changeset

  alias Orcasite.Radio.{Feed, Candidate}
```

**Comment by scottveirs** [comment]
Listening live today and trying to quickly switch to the Orcasound web app tab, I'm observing two things that could guide slight improvements to the human detection functionality, as well as the candidate review feature in the `admin` UI:

1. Upon hearing a nifty sound that I want to label, it takes me a few seconds (sometimes 5-10...) to find the browser/tab with the web app playing live sound and press the "I hear something interesting" button.
2. Comparing the live audio stream of fish grunts with the 10s candidates I hoped/expected would contain them, it's becoming clear to me that in some cases the .ts segment(s) that are presented in the `admin` review UI's player are often too late to contain the signal that inspired me to label.

An enhancement might be to prepend an additional segment (e.g. ~10 seconds) to the candidate as it currently built. This might help capture a bit of audio data before the signal of interest, the signal itself, and a bit of context after it.

**Comment by paulcretu** [comment]
Fixed in https://github.com/orcasound/orcasite/pull/167 (more specifically https://github.com/orcasound/orcasite/pull/167/commits/7682c363e42e9fc051c42a75b004e0537b69912f and https://github.com/orcasound/orcasite/pull/167/commits/9628583ba9d0f14f28e07a1b5785c7e9da0c5676)

Some more ideas for future improvements (new issues?):
- Display the timestamp that was registered when the dialog opened (maybe as "x seconds ago" field)
- Provide a small inline player in the modal/dialog, so users can choose exactly when to annotate (too complicated?)
- Prepending is a good idea, something to implement when candidates UI is re-added
- It would be good to somehow tag detections that are pre-bugfix—though I expect that this fix will roll out with v3 launch so that's probably a good enough milestone
