### ISSUE TITLE
"I hear something interesting" prompt is accepting empty values on listen live page.

### ISSUE THREAD

**Issue by aashimawadhwa** [orcasound/orcasite#89]
**Describe the bug**
"I hear something interesting" prompt is accepting empty values on listen live page.

**To Reproduce**
1. Go to listen live button
2. Click on listen live tab
3. Select any from the drop down menu.
4. click on play icon and then i hear something interesting .
5. submit it empty.
6. See error

**Expected behavior**
it should validate the field before submitting and display some error message if empty.

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/73706697/153770484-492295be-bbac-4d4b-b51c-025fa4a85b60.gif)

**Comment by Aayushd18** [comment]
Hi. I would like to work on this issue.

**Comment by paulcretu** [comment]
Thanks for the report @aashimawadhwa! However, I'm not actually sure this is a problem—I think it's fine for users to submit empty reports, as it's still valuable information and we can always filter it out later.

Also this is UI is getting completely rebuilt so there's no point in making any non-critical changes to the old UI. As a result I'm closing this out as `wontfix`
